### ISSUE TITLE
Scoreboard after match

### ISSUE THREAD

**Issue by BacLuc** [sopra-fs22-group-36/screw-your-neighbor-server#11]
As a player in a game, I can see a scoreboard with my and the others points after every match in order to see my performance so far.

- [x] The game counts the points in a correct way.
- [x] The game counts the points after a match.
- [x] For each player the distribution of the points is visible in the scoreboard. 

Related to #9

**Comment by MorisCamporesi** [comment]
>  The game counts the points in a correct way.
-validate that https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/148 has no influence then close
>  The player can see on a scoreboard which can displayed by a button.
> For each player the distribution of the points is visible in the scoreboard.

-eventuell rausnehmen?

**Comment by BacLuc** [comment]
> > The game counts the points in a correct way.
> 
> -validate that #148 has no influence then close

Validated: it only affected the turnActive flag.

> 
> > The player can see on a scoreboard which can displayed by a button.
> > For each player the distribution of the points is visible in the scoreboard.
> 
> -eventuell rausnehmen?
-> entfernt
