### ISSUE TITLE
Create User Account

### ISSUE THREAD

**Issue by BacLuc** [sopra-fs22-group-36/screw-your-neighbor-server#14]
As a player, I can create an account on the app in order to change my user credentials. 

- [ ] When a player without a user account visits the app, he can click on a button called “Register”. 
- [ ] This button takes him to a page where he can register his username and password.
- [ ] He can change hisname, username and password.

Tracked in frontend: https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/92
and backend: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/151

**Comment by elBeato** [comment]
We are closing this issue without an implementation. The reasons are varied:
1. No added value for the fun of the game
2. Heroku does not have a persistent DB
3. All common games in this form are played without registration.
4. We have already implemented user account login and registration in M1.
5. Low priority

It took place in consultation with our TA.
