### ISSUE TITLE
Add Validations in Backend

### ISSUE THREAD

**Issue by BacLuc** [sopra-fs22-group-36/screw-your-neighbor-server#140]
As a user, i want to see an error message if i made an invalid interaction.

- [x] Validations for Game
  - [x] #160
  - [x] #169
  - [x] #170
  - [x] #166
  - [x] #49
- [ ] #63
- [x] #56 
- [x] Validations for Player
  - [x] If the active session already contains a player, one cannot create another player
  - [x] #167

- [x] Access Control: protect all endpoints except the ones for development, the hello world endpoint and the endpoints for the creation of the player and the check if a session exists

- [x] #185

- [x] #193

**Comment by BacLuc** [comment]
@salwil, @elBeato, @MorisCamporesi, @CarmenUZH : i stared moving the validations out of the previous stories, that we can close them, and start with the validations from here.

**Comment by elBeato** [comment]
Add in ReadMe as contribution options: Validations for announcing the score #63
