### ISSUE TITLE
Non-battling round has all players turns active

### ISSUE THREAD

**Issue by salwil** [sopra-fs22-group-36/screw-your-neighbor-server#163]
From https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/pull/161#issuecomment-1124728530

![image](https://user-images.githubusercontent.com/45465496/168034989-d5458e6b-e722-419c-96a1-75d5c20934fe.png)

@BacLuc could you please provide details? When does scenario happen? What type of round? (regular round, stacked round, in the beginning of a new round, after already some players have played their cards in a round...)

**Comment by BacLuc** [comment]
Is fixed with https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/pull/161/commits/1726c92bcc252c328cb1e8d1b88d8e06741eb96e
