### ISSUE TITLE
Invite link to game room

### ISSUE THREAD

**Issue by BacLuc** [sopra-fs22-group-36/screw-your-neighbor-server#17]
As a player, I want to be able to invite other players into my current lobby in order to start the game without a long waitingtime. 

- [x] When a player is in a lobby there is a button called “invite other players”. https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/46
- [x] ~~When clicking this button, the player sees a list of registered users that are currently online. ~~ When clicking this button, a link to invite other people is generated and saved to the players clipboard. https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/91
- ~~[ ] When clicking on one of these players, said player gets an invite to the lobby.~~
- ~~[ ] when the invited player looks at the list of available lobbies, the lobby he was invited to changes colour to notify him of the invitation. ~~

**Comment by MorisCamporesi** [comment]
> When clicking this button, the player sees a list of registered users that are currently online.
> When clicking on one of these players, said player gets an invite to the lobby.
> when the invited player looks at the list of available lobbies, the lobby he was invited to changes colour to notify him of the invitation.

Wollen wir das noch so umsetzen? Haben zurzeit noch keine User, ich würde eher in Richtung: "link erstellen, wenn man dem folgt landet man direkt in dem room" gehen.

**Comment by BacLuc** [comment]
> > When clicking this button, the player sees a list of registered users that are currently online.
> > When clicking on one of these players, said player gets an invite to the lobby.
> > when the invited player looks at the list of available lobbies, the lobby he was invited to changes colour to notify him of the invitation.
> 
> Wollen wir das noch so umsetzen? Haben zurzeit noch keine User, ich würde eher in Richtung: "link erstellen, wenn man dem folgt landet man direkt in dem room" gehen.

Wäre ich auch dafür: nur noch einen link machen, mit dem man direkt einen Room joinen kann (sofern er noch offen ist).
